ynput/ayon-deadline

- client/ayon_deadline/plugins/publish/submit_aftereffects_deadline.py
- client/ayon_deadline/plugins/publish/validate_expected_and_rendered_files.py
Fix missing `settings_category = "deadline"` attribute for plug-ins that do appear in settings
1. Settings should work for After Effects submissions plug-in `AfterEffectsSubmitDeadline`
2. Settings should work for `ValidateExpectedFiles` for renders
> Add missing settings category

- client/ayon_deadline/plugins/publish/submit_houdini_cache_deadline.py
- client/ayon_deadline/plugins/publish/submit_houdini_render_deadline.py
- client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
If -use-staging is used in published job, this will propagate it to the AYON process for environment extraction. 
Must use command line argument, environment variable won't get picked up.
This requires redeploy of `GlobalJobPreLoad.py`!
> Pass staging as settings variant

- client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
Do not force the full job to fail - it may be just this machine has a server connection timeout.
This allows a single machine to fail - yet others to continue in the queue.
This also allows a single machine to try again - since it'll use Deadline's default "mark bad after X errors" setting to decide when a worker is 'bad'.
Fix #14
1. Submit job to Deadline
2. Turn off your AYON server (or do whatever to make the GlobalJobPreLoad fail)
3. It should not instantly mark the full job and all its task "failed"
> Do not fail job on error in GlobalJobPreLoad

- client/ayon_deadline/plugins/publish/global/submit_publish_cache_job.py
- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
- server/settings/publish_plugins.py
Publish jobs are always single, doesn't make sense to set something different.
Removed obsolete `publishing_script` too.
1. publish something in DL, shouldn't fail
> Removed chunk size from publish jobs

- client/ayon_deadline/plugins/publish/global/collect_default_deadline_server.py
[deadline_addon.deadline_servers_info](https://github.com/ynput/ayon-deadline/blob/bb0d1929836a172d712223f2d781278055a017e9/client/ayon_deadline/plugins/publish/global/collect_default_deadline_server.py#L43-L44) seems to be a dictionary so accessing items through indexes as if it was a list raises an error.
1. start with this step
2. follow this step
> Collect server url: Access server info correctly

- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
This is hotfix to support publish jobs working in staging mode.
This issue is down the line connected to wrong implementation of AYON launcher not respecting `AYON_DEFAULT_SETTINGS_VARIANT` environment variable.
1. Validate changes made in code.
2. Create package, upload to server and use in staging bundle.
3. Submit job from staging.
4. Publish job should use staging addon versions and settings.
> Publish jobs respect staging mode

- client/ayon_deadline/plugins/publish/max/submit_max_deadline.py
Relevant to https://github.com/ynput/ayon-3dsmax/pull/13
This PR is to fix the bug of using same camera across the scenes in 3dsmax when multicamera option is enabled, while resolving the special characters are not allowed as being the render output and scene file names
Resolve https://github.com/ynput/ayon-3dsmax/issues/12
Test along with https://github.com/ynput/ayon-3dsmax/pull/13
1. Build and install deadline addon with this branch
2. Publish render with multicamera option enabled in 3dsmax
> Make sure multicamera render from 3dsmax uses correct camera in farm submission

- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
- server/settings/publish_plugins.py
Do not pass ftrack family to publish instance.
It is job of ftrack addon to care about it. Collect ftrack family should be running on farm too, or I might miss something?
1. Create package, upload to server, add to bundle (with ftrack addon).
2. Send job to deadline that should create review.
3. The review should go to ftrack.
> Review: Don't pass ftrack family to jobs

- client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py
Collect farm env variables does not override already set environment variables.
1. Environment variables should be passed to jobs correctly.
> Chore: Don't override already set env variables

- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Fixing `Use existing frames` Nuke workflow where there is no first render submission
Solves 
```
submit_nuke_deadline.py", line 101, in process
response_data = instance.data["deadlineSubmissionJob"]
KeyError: 'deadlineSubmissionJob'
```
1. set  `Use existing frames`  in Nuke
2. publish, shouldnt fail
> Fix use existing frames workflow in Nuke

- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
This fixes artist override of explicit range of frames to be rendered via Publisher UI. It was not working in Nuke.
1. set some limited range in `Frames` box in Publisher in Nuke
2. check `Frames` in `Submission Params` in Deadline submission
> Use explicit range of frames to render in Nuke

- client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
Force disable Houdini USD render to not use the published file for rendering
Fixes #82
1. Submit Houdini usd render
2. Publish should succeed regardless of "Use Published" setting in default profiles
> Force disable Houdini USD render to not use the published file for rendering

- client/ayon_deadline/plugins/publish/harmony/submit_harmony_deadline.py
This fixes doubling of frames in Deadline rendered files from Harmony
Logic is looking for static portion of output path, eg. it wants to remove frame info + extension
1. publish to Deadline from Harmony
> Fix wrong pattern for frames and ext in Harmony

- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
This returns changed render job names to original state. Nuke has different format than the rest.
Question is, if this naming is not actually better than universal one, where `Batch Name - InstanceName` value is used.
1. trigger Nuke Deadline job
2. render jobs should be named according to files they are rendering
(`renderNuke_compositingMain.baking.mov` vs `ad_sh01_nuke_compositing_v047.nk - renderNuke_compositingMain`)
> Fix names of render jobs for Nuke

- client/ayon_deadline/addon.py
- client/ayon_deadline/lib.py
- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
Fix #103 
Limit Groups and Groups were swapped in the Server Info.
1. Expose groups and limit groups in the UI.
2. They should behave accordingly and be correctly submitted along to the job.
> Fix Collect Job Info Groups and Limit Groups

- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
- client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
Fix Maya submit strict error checking and tile priority attributes
- They are now adhered to in publisher UI
- They are now based on the SubmitMayaDeadline settings in AYON
- They are now not incorrectly 'hidden' in `JobInfo` instance even though they are Plugin Info attributes
There is the downside that they are now in a not very nice location in the Publisher UI itself (because they are not part of the "Job Info" collector now.
---
Originally reported on discord [here](https://discord.com/channels/517362899170230292/563751989075378201/1326631657494548482)
1. Tweak 'strict error checking' defaults in settings
2. Publisher UI should adhere to those defaults for submitting maya render
3. Submit from Maya
4. The job should adhere to the publisher UI values.
> Fix Maya submit strict error checking and tile priority attributes

- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
- server/settings/publish_plugins.py
Baking job should have only once instance, one task.
(sys.maxsize didnt work, hopefully this value will be enough).
1. in Nuke set ChunkSize to some small value to actually trigger (eg. it should produce multiple tasks for render job)
2. check that `Baking` job still has only single task, baking whole frame range.
> Updated ChunkSize for baking jobs to 999999

- client/ayon_deadline/plugins/publish/harmony/submit_harmony_deadline.py
Published workfile needs to be used for Deadline rendering as real incremented version of workfile is not created only after DL submission.
This PR moves intermediate rendered frames to `work` area in similar fashion as other DCCs.
~~This PR requires (https://github.com/ynput/ayon-harmony/pull/20)
For now it should be handling presence of that Harmony addon version safely, it will be cleaned up before full release.~~
Replaced by AYON_WORKDIR env var.
1. publish to DL
2. check that workfile is unzipped in `work/TASK_NAME/renders/harmony/VERSIONED_FOLDER
> Harmony: Render to workdir instead of publish dir

- client/ayon_deadline/abstract_submit_deadline.py
- client/ayon_deadline/addon.py
- client/ayon_deadline/constants.py
- client/ayon_deadline/lib.py
- client/ayon_deadline/plugins/publish/global/collect_deadline_server_from_instance.py
- client/ayon_deadline/plugins/publish/global/collect_default_deadline_server.py
- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
- client/ayon_deadline/plugins/publish/global/collect_user_credentials.py
- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
- client/ayon_deadline/plugins/publish/global/validate_expected_and_rendered_files.py
- client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
- client/ayon_deadline/plugins/publish/houdini/submit_publish_cache_job.py
- client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Added api functions to submit deadline jobs using server name from settings.
Also used new functions in publish jo submission plugins. That required small change in server collection to also store `serverName` to deadline info on instance and context, in future, we could store only server name.
The functionality can be also used for submission of render jobs. New api functions were added to allow other addons trigger AYON plugin jobs without knowing too much.
1. It is possible to submit publish job.
2. Submitted publish job should work as before.
> Chore: Add submit api functions

- client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
Fix submission of multiple fusion render instances in one go by also storing `instance.data["deadline"]` correctly to each instance
Fixes error:
```python
Traceback (most recent call last):
File "C:\Users\Maqina-RTX-05\AppData\Local\Ynput\AYON\dependency_packages\ayon_2407291312_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
runner(*args)
File "C:\Users\Maqina-RTX-05\AppData\Local\Ynput\AYON\addons\deadline_0.5.1+cb.1\ayon_deadline\plugins\publish\global\submit_publish_job.py", line 418, in process
representations = prepare_representations(
File "C:\Users\Maqina-RTX-05\AppData\Local\Ynput\AYON\addons\core_1.0.10+cb.1\ayon_core\pipeline\farm\pyblish_functions.py", line 340, in prepare_representations
frames_to_render = …
```
> Fusion: Fix submission of multiple fusion render instances

- client/ayon_deadline/plugins/publish/global/collect_deadline_server_from_instance.py
`setdefault` checks only for presence of key, not if value is None, which now happens in Fusion and Unreal. This way is safer, until Fusion/Unreal and default values for RenderInstance are fixed in ayon-core.
`ayon-core` `RenderInstance` sets `deadline` key to None, but should set it as {}. 
1. publish in Fusion/Unreal
2. shouldnt fail in `collect_deadline_server_from_instance`
> Update setting default value for deadline dict on instance

- server/settings/publish_plugins.py
Without it nothing (`Priority`, `Pool` etc)  would show up in Publisher UI
1. redeploy addon
2. Check if you can see `JobInfo` properties in Nuke Publisher UI
> Added overrides for 2D DCC in Collect JobInfo

- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
This PR populates a publish instance's UI for `Primary Pool` and `Secondary Pool` from the `Collect JobInfo` profiles.
Addressed issue https://github.com/ynput/ayon-deadline/issues/85
1. define a JobInfo profile with values set in `Primary Pool` and `Secondary Pool`
2. expose these attributes
3. open a dcc and create a supported product type (render)
4. check the publish items UI for the exposed values and check whether they correspond with the server settings
> Publish UI populates pools from server settings

- client/ayon_deadline/abstract_submit_deadline.py
- client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
`jobInfo.OutputDir` now uses possibly remapped values of `expectedFiles`. 
`jobInfo.Output` now contains only single value, not one per `expectedFiles` file.
It could happen that published workfile has different name than work workfile, `_set_scene_path` remaps `expectedFiles` to name of published workfile, `OutputDir` value was set before, eg. didn't respect that.
Not sure about Houdini and Max, there are some discrepancies I didn't want to touch. Could be modified in later PRs though.
1. publish in DCC of your choice to DL
2. check that `Job Output > Explore Job Output` in DL Monitor points to expected folder.
> Job Info Output Directory+Files pass sequence and remap to published workfile if needed

- server/settings/publish_plugins.py
Change order of attributes in submit publish job plugins to match order in CollectJobInfo settings.
Different order of attributes lead to wrong assignment of values (pool <-> group) and I agree that the order should follow same order. Because I think the order in CollectJobInfo makes more sense I've changed submit publish job accordingly.
Technically nothing changed, only settings UI shows attributes in different order.
> Settings: Change settings attributes in submit publish job plugin

- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Without it baking job wouldnt wait for rendering job.
1. render in Nuke with Deadline
2. check baking `Job properties > Dependencies`, there should be job with name from rendering job
> Fix assignment of job dependency

- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Provides simple one logging line about where `metadata.json` for publishing job is stored. 
1. publish to Deadline
2. check log for `Submit Image Publishing job to Deadline`
> Added logging for location of metadata.json

- client/ayon_deadline/abstract_submit_deadline.py
- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
If published workfile is used for rendering, it shouldnt update path of explicit custom staging dir.
Should be tested together with https://github.com/ynput/ayon-nuke/pull/58
1. set `ayon+settings://core/tools/publish/custom_staging_dir_profiles` for your DCC of choice to use custom staging dir
2. publish to DL
3. check that `OutputDirectory0` still points to that folder
> Do not update expected files if custom staging dir

- client/ayon_deadline/plugins/publish/aftereffects/submit_aftereffects_deadline.py
New implementation in abstract_submit_deadline forces `replace_in_path` argument.
Found by automatic tests.
1. publish with AE in DL
2. shouldnt fail
> AE Submit job: Fix method signature

- client/ayon_deadline/addon.py
- client/ayon_deadline/lib.py
- client/ayon_deadline/plugins/publish/global/validate_deadline_connection.py
- client/ayon_deadline/plugins/publish/global/validate_deadline_pools.py
We currently have the `Don't verify SSL` option in the AYON Deadline plugin enabled for our studio, but found when testing with Maya that the plugins validating the Deadline connection and pools would not pass the `verify=False` flag down to requests and so were borking out with SSL verification errors.
This PR (somewhat clumsily - but it was the cleanest way I could without any `lib.py` refactor) passes that flag down from settings into each of the calls made by the authentication plugins.
> Ensure that SSL verification setting is respected by all plugins.

- client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py
- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
- client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
GlobalPreLoadJob.py does respect `AYON_USE_STAGING` environment variable as replacement for `AYON_DEFAULT_SETTINGS_VARIANT`.
Environment variable `AYON_DEFAULT_SETTINGS_VARIANT` is still used for backwards compatibility. It is also explicitly set by deadline addon now, so ayon-core does not have to set it up for future deprecation.
This change is preparation for future cleanup that can't happen now to keep backwards compatibility.
We need to know if AYON process should happen as production, staging or dev. Dev is defined just by bundle name, production is also defined only by bundle name, and staging needs bundle name and `AYON_USE_STAGING`, so we don't need `AYON_DEFAULT_SETTINGS_VARIANT` at all if we have `AYON_BUNDLE_NAME` and `AYON_USE_STAGING` available.
We need to support backwards …
> Chore: Use 'AYON_USE_STAGING'

- client/ayon_deadline/addon.py
Removes trailing issue in Deadline server url which caused issue in retrieval of `api/jobs` in `Submit Image Publishing job to Deadline`
1. set Deadline server url with trailing slash
2. publish via DL
> Fix: remove trailing slash in host url

- client/ayon_deadline/lib.py
- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
- client/ayon_deadline/plugins/publish/houdini/submit_publish_cache_job.py
- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
- server/settings/publish_plugins.py
Publish job could be set as `Suspended` to allow artist publish only after some necessary checks are made. This was previously possible only in Publisher UI, but even that was removed during refactoring.
Now state of Publish job could be controlled by `Collect Job Info` configuration with Profiles and could be overridden by artist in Publisher UI if necessary.
1. experiment with `ayon+settings://deadline/publish/CollectJobInfo/profiles/1/publish_job_state`
2. check that values propagate to Publisher UI in DCC, try to change it
3. publish in Deadline and check state of published job in DL Monitor
> Added possibility to control state of Publish job in Settings and Publisher UI

- client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.param
- client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.py
- client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
Do not override `ayon_server_url` variable before logging it.
If using a custom job url the logs should now not report the job url twice, but actually would report the 'default ayon url' to compare with. That fixes the log, and greatly clarifies the actual message too.
Requires updating the `GlobalJobPreLoad.py` on your Deadline repo.
#42 implemented the feature originally.
1. If using a custom job url the logs should now not report the job url twice, but actually would report the 'default ayon url' to compare with. That fixes the log, and greatly clarifies the actual message too.
> Fix logging correct default `ayon_server_url` in the logged message

- server/settings/publish_plugins.py
Add default for `publish_job_state`
Fixes a case where if existing overrides existed in settings **without** the `publish_job_state` key that it now adds this default value.
Fixes:
```
025-02-18 10:18:47 ERROR      server          Unable to load deadline 0.5.5 settings
Traceback (most recent call last):
File "/backend/api/settings/settings.py", line 172, in get_all_settings
settings = await addon.get_project_settings(project_name, variant)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/ayon_server/addons/addon.py", line 451, in get_project_settings
settings = await self.get_studio_settings(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/ayon_server/addons/addon.py", line 435, in get_studio_settings
settings = apply_overrides(settings, overrides) …
```
> Add default for `publish_job_state`

- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Submit publish job does not set `OutputDirectory` if template cannot be filled.
The reason why template cannot be filled may wary, one usecase might be that studio uses `{representation}` in directory template, which is not available when submitting job.
1. Use `{representation}` in `directory` publish template.
2. Submit job to deadline.
3. Job should be submitted without output directory, and the publishing does not crash.
> Publish job: Ignore unfilled output dir

- client/ayon_deadline/lib.py
- client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
This fixes LimitGroups not being passed on to the Deadline Job. It also fixes the LimitGroups if `Node Based Limit Groups` are enabled in Nuke.
I think the UI/UX can be better for defining the `Node Based Limit Groups`. At first I confused the Limit Name with the Node Class. 
It's actually not the LimitGroup your set as the value to the LimitGroup key, but the Node Class in Nuke.
1. define Deadline Limit to use in `Collect JobInfo` profiles
2. define custom node-based limit in `Nuke Submit to Deadline` server settings
2. submit to Deadline and check the jobs' limits
> Fixes LimitGroups and Node-Based LimitGroups in Nuke

- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
- server/settings/publish_plugins.py
`JobDelay` wasn't passed in, list of Denied workers weren't passed in
`JobDelay` is a bit difficult to check, see:
1. experiment with JobDelay and Machine list is a Deny in `Collect JobInfo Settings`
2. check if they are passed in correctly
> Fix: passing of JobDelay and Machine list is a Deny

- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
`CollectSceneVersion` could be disabled for DCC so version on context might not be collected.
See https://github.com/ynput/ayon-nuke/issues/78 for more details.
1. disable `ayon+settings://core/publish/CollectSceneVersion` your DCC of choice (Nuke will ignore it - in `CollectContextData` - different question - PR)
2. publish to DL
3. check version of published files
> Version on context could be optional

- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
Without it fails with weird missing key error ('chunk_size', but might be different). Error message now points to real problem
Now it fails with 
1. remove all profiles at `ayon+settings://deadline/publish/CollectJobInfo`
2. try to publish anything to DL, should get better error message
> Fix: if no profiles for CollectJobInfo found

- client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
Support farm submissions for `image` product type
Fix https://github.com/ynput/ayon-deadline/issues/140
**Warning!** There is a caveat that the Fusion Deadline Render plug-in renders all tools in one go from one scene, and does not support setting a frame range per tool. Hence, if you were to mix "image" products with "render" products from one comp file and submit them both together - it doesn't actually influence the render frame ranges.
The render frame range is currently taken from the **first** instance. This is also an existing bug with "Render" instances with different frame ranges. 
1. Submit "image" products to the farm.
2. Publish should be successful.
> Support farm submissions for `image` product type

- client/ayon_deadline/plugins/publish/global/collect_user_credentials.py
Make `Collect Deadline User Credentials` run on all hosts if matching families, like other deadline plug-ins
Avoids hitting:
```python
Traceback (most recent call last):
File "C:\Users\User\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
runner(*args)
File "F:\dev\ayon-deadline\client\ayon_deadline\plugins\publish\global\validate_deadline_pools.py", line 42, in process
instance.data["deadline"]["verify"]
KeyError: 'verify'
```
When working with new hosts.
1. Change should be validated in hosts where it previously would not have run.
> Make `Collect Deadline User Credentials` run on all hosts

- client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Write `version` into the publish job metadata if version is 0
May fix https://github.com/ynput/ayon-core/issues/1203
1. set version start to zero for Nuke _ayon+settings://core/version_start_category_
2. Launch Nuke, publish to farm
3. Publish should succeed and 'version' should be present in metadata.json
> Write `version` into the publish job metadata if version is 0

- client/ayon_deadline/repository/custom/plugins/UnrealEngine5/UnrealEngine5.py
Fix typos in Unreal Engine process. 
Fix missing variable "cmd_args".
Seems like the file was modified before it was copied from the official repo, as it has some changes that are not there. It's logging some extra information with typos.
There was also a missing variable that looks to have been replaced at some point. I reverted this to how it is in the original.
> Unreal Engine: Fix typos in logs

- client/ayon_deadline/repository/custom/plugins/UnrealEngine5/UnrealEngine5.py
Handle errors for when ProRes fails to write a file, and errors where the engine closes for some reason.
Without these error handlers deadline will just spit out a generic error:
```
Only one usage of each socket address (protocol/network address/port) is normally permitted
```
Which doesn't really tell you much.
A bit hard to test these ones, but we have been running with these for a while and it makes it easier to tell what is causing the error.
> Unreal Engine: Add error handlers for ProRes Error and Windows exit issues 

- client/ayon_deadline/abstract_submit_deadline.py
Chore: Add some type hints to `AbstractSubmitDeadline.__init__` so attribute access provide better type hints
IDE should provide better hints.
Publishing should still work
1. Publishing should still work
> Chore: Add some type hints to `AbstractSubmitDeadline.__init__`

- client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
- server/settings/publish_plugins.py
Allow `concurrent_tasks` as exposed override in publisher UI for Collect Job Info
Fix #163 
1. Enable "Concurrent Tasks" as exposed override in settings.
2. The setting should become visible in publisher UI.
3. It should have the default as the default value set in settings.
4. When changing the value in publisher UI the published job should adhere to the concurrency value.
> Allow `concurrent_tasks` as exposed override in publisher UI for Collect Job Info

- client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
Maya: Patch workfile - fix comparison for `.ma` file extension
Otherwise it'd run on `.mb` files and error and never be able to run on a `.ma` either. So basically this feature has been broken in... forever?
Came up internally [here](https://discord.com/channels/517362899170230292/1364938325873524848/1364940468814876672) (private conversation)
Example traceback when running on `.mb` file:
```python
//   File "/usr/autodesk/maya2025/lib/python3.11/encodings/ascii.py", line 26, in decode
//     return codecs.ascii_decode(input, self.errors)[0]
//            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 35: ordinal not in range(128)
// Traceback (most recent call last):
//   File …
```
> Maya: Patch workfile - fix comparison for `.ma` file extension

- client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
Support new `render` product types in Houdini
Fix for change coming with https://github.com/ynput/ayon-houdini/pull/214
Fix issue described [here](https://github.com/ynput/ayon-houdini/pull/214#issuecomment-2807662733)
1. Houdini submitted deadline renders should still work for "split render job"
> Houdini Render: Support `render` product types for Creators

- client/ayon_deadline/plugins/publish/global/collect_user_credentials.py
- server/settings/main.py
Fixed displaying all configured Deadline servers from `Studio Settings` and enhancing `Project Settings` `Site Settings` to allow artists (freelancers) to use different than selected DL server on the project. 
(Maybe freelancers need to use different exposed IP or port.)
Enhancing of `Project Settings` `Site Settings` was selected as it automatically propagates value configured on `Project Settings`. 
Another option would be `Studio Settings` . `Site Settings` would be more complicated as it requires default value which would need to be hardcoded and maybe non existent. (If 'default' would be used, we cannot rely that 'default' actually exists and no studio admin wouldn't rename it right away.)
1. configure more DL servers in `ayon+settings://deadline/deadline_urls`
2. select newly …
> Artists can override selected Deadline server

- client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.py
- client/ayon_deadline/repository/custom/plugins/Ayon/__init__.py
- client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
If `Additional AYON Servers` configuration was used, AYON_API_KEY weren't picked up for Publish job. This limited that functionality as it would be working only for same key values on all servers.
0. Redeploy `https://github.com/ynput/ayon-deadline/tree/develop/client/ayon_deadline/repository/custom/plugins` to `DL_REPO/custom/plugins`
1. enable `ayon+settings://deadline/publish/CollectAYONServerToFarmJob`
2. break AYON_SERVER_URL and AYON_API_KEY values in AYON Deadline plugin configuration
3. fill working combo to `Additional AYON Servers` in DL AYON plugin configuration
4. publish
Issue: YN-0013
> Fix: AYON_API_KEY from Additional AYON Servers is used for Publish jobs

- package.py
Revert houdini version compatibility added in https://github.com/ynput/ayon-deadline/pull/201 .
Deadline is still compatible with older versions of houdini addon.
1. Use older houdini addon versions that what is defined in package.py .
2. Farm publishing should work just fine.
> Chore: Remove houdini version compatibility

- client/ayon_deadline/addon.py
This caused issue if no credentials were provided.
It raised KeyError on `default_username` as local server_info overshadowing main one doesn't have any `default_username`.
1. Set `ayon+settings://deadline/deadline_urls` requiring authentication
2. enable authenticcation on DL
https://help.ayon.app/articles/5372986-configure-deadline-addon#wc4i7beia26
3. provide no user credentials in `Studio Settings > Site Settings`
4. submission to DL shouldnt fail
> Fix shadowing of server_info with local settings
